### PR TITLE
Update working-memory.md from the data lab.

### PR DESCRIPTION
**Pull request by DrescoAV**
Changed the wrong value of the variable "a" in the explained comment from "7" to "42".

### CODE REVIEW

**Review by teodutu — CHANGES_REQUESTED** [review]
Thanks for the fix! What you need to do to make the checkpatch test pass [1] is to:

1. `git commit --amend` and wrap the commit's description on 2 lines so that the first one doesn't exceed 75 characters
2. add the following line to your commit message:

```
Signed-off-by: <Your Name> <your email>
```

To do so, configure your user name and email like so:
```
git config --global user.name "Your Name"
git config --global user.email "your email"
```

Then run `git commit --amend -s` to add the signed-off line automatically to your last commit. Then ensure your name and email are set on GitHub like those you've just set locally. Finally, use `git push -f` to replace your existing upstream commit with the one you've just amended. Then check the workflow runs to be all green.

[1] https://github.com/cs-pub-ro/operating-systems/actions/runs/6658249408/job/18109132144#step:3:566

**Comment by teodutu** [comment]
I'm not sure how you ended up with that second commit you've just pushed. Anyway, it's empty so you can just run `git reset HEAD^ --hard` followed by `git push -f` to remove it both locally and upstream. Did you try following the steps I told you about here [1]? Did you get any errors?

[1] https://github.com/cs-pub-ro/operating-systems/pull/14#pullrequestreview-1702384515

**Comment by DrescoAV** [comment]
> I'm not sure how you ended up with that second commit you've just pushed. Anyway, it's empty so you can just run `git reset HEAD^ --hard` followed by `git push -f` to remove it both locally and upstream. Did you try following the steps I told you about here [1]? Did you get any errors?
> 
> [1] [#14 (review)](https://github.com/cs-pub-ro/operating-systems/pull/14#pullrequestreview-1702384515)

I pressed on sync fork and it auto-updated it, that's why there was a second commit. Thanks for letting me know how to revert it. Is it ok now?

**Review by teodutu — CHANGES_REQUESTED** [review]
Almost there. Keep your commit description and signature the way they are and use `git commit --amend` once more to edit the commit title (the first line) to something more explanatory such as `data/lab: Fix typo`.

**Review by teodutu — APPROVED** [review]
perfect

**Pull request merged**
