### PR TITLE
chapters/software-stack: Fix `common-functions` task.

### PR DESCRIPTION
**Pull request by teodutu**
# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

- Add `main_string.c` and `string.*` to be used in the `reading/` activity.
- Fix `main_printf.c` to inlcude the system header `string.h` and not the local file.

### CODE REVIEW

**Comment by mariapana** [comment]
`make check` fails with:
```
test_strcat.c: In function ‘test_strcat_return’:
test_strcat.c:16:13: warning: implicit declaration of function ‘os_strcat’; did you mean ‘os_strcpy’? [-Wimplicit-function-declaration]
   16 |         p = os_strcat(dest, src);
      |             ^~~~~~~~~
      |             os_strcpy
test_strcat.c:16:11: warning: assignment to ‘char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   16 |         p = os_strcat(dest, src);
      |           ^
test_strcat.c: In function ‘test_strcat_data’:
test_strcat.c:39:17: warning: implicit declaration of function ‘strcmp’ [-Wimplicit-function-declaration]
   39 |         return !strcmp(dest, "xyzabcd");
      |                 ^~~~~~
test_strcat.c:9:1: note: include ‘<string.h>’ or provide a declaration of ‘strcmp’
    8 | #include "graded_test.h"
  +++ |+#include <string.h>
    9 | 
cc -Wall -Wextra -g -O0 -I. -I/home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/src -I../utils  -c -o graded_test.o graded_test.c
cc  -o test_strcat test_strcat.o graded_test.o /home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/src/os_string.o ../utils/log/log.o 
/usr/bin/ld: test_strcat.o: in function `test_strcat_return':
/home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/tests/test_strcat.c:16: undefined reference to `os_strcat'
/usr/bin/ld: test_strcat.o: in function `test_strcat_len':
/home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/tests/test_strcat.c:27: undefined reference to `os_strcat'
/usr/bin/ld: test_strcat.o: in function `test_strcat_data':
/home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/tests/test_strcat.c:37: undefined reference to `os_strcat'
collect2: error: ld returned 1 exit status
make[1]: [Makefile:18: test_strcat] Error 1 (ignored)
make[1]: Leaving directory '/home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/tests'
```

**Comment by teodutu** [comment]
> `make check` fails with:
> 
> ```
> test_strcat.c: In function ‘test_strcat_return’:
> test_strcat.c:16:13: warning: implicit declaration of function ‘os_strcat’; did you mean ‘os_strcpy’? [-Wimplicit-function-declaration]
>    16 |         p = os_strcat(dest, src);
>       |             ^~~~~~~~~
>       |             os_strcpy
> test_strcat.c:16:11: warning: assignment to ‘char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
>    16 |         p = os_strcat(dest, src);
>       |           ^
> test_strcat.c: In function ‘test_strcat_data’:
> test_strcat.c:39:17: warning: implicit declaration of function ‘strcmp’ [-Wimplicit-function-declaration]
>    39 |         return !strcmp(dest, "xyzabcd");
>       |                 ^~~~~~
> test_strcat.c:9:1: note: include ‘<string.h>’ or provide a declaration of ‘strcmp’
>     8 | #include "graded_test.h"
>   +++ |+#include <string.h>
>     9 | 
> cc -Wall -Wextra -g -O0 -I. -I/home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/src -I../utils  -c -o graded_test.o graded_test.c
> cc  -o test_strcat test_strcat.o graded_test.o /home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/src/os_string.o ../utils/log/log.o 
> /usr/bin/ld: test_strcat.o: in function `test_strcat_return':
> /home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/tests/test_strcat.c:16: undefined reference to `os_strcat'
> /usr/bin/ld: test_strcat.o: in function `test_strcat_len':
> /home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/tests/test_strcat.c:27: undefined reference to `os_strcat'
> /usr/bin/ld: test_strcat.o: in function `test_strcat_data':
> /home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/tests/test_strcat.c:37: undefined reference to `os_strcat'
> collect2: error: ld returned 1 exit status
> make[1]: [Makefile:18: test_strcat] Error 1 (ignored)
> make[1]: Leaving directory '/home/mia/Desktop/SO/operating-systems/chapters/software-stack/libc/drills/tasks/common-functions/support/tests'
> ```

This is intended. It's meant to show what happens when a function is referred but neither declared, nor implemented. Students should do both. Do you think it should be more verbose about this?

**Comment by mariapana** [comment]
It seemed unintentional to them, perhaps some clarifications in the text for the tasks would be better?

Also, the demo with `strace ./main_printf` doesn't work properly. The whole string of characters gets printed instead of chr by char as shown in the reading section.

**Comment by teodutu** [comment]
> Also the demo for `strace ./main_printf` in `common-functions` doesn't match the reading section (the system calls don't occur for each character, but for the whole string).

I think that has always been an error. I've fixed it now.

**Comment by mariapana** [comment]
I don't think you pushed the fix for the `main_printf` demo. Other than that LGTM.

**Comment by teodutu** [comment]
@mariapana give this another go now. I also fixed `_putchar()` to `write()` a single character at first.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
