### PR TITLE
general/drills: Add "Network Performance Utility" written task as exam

### PR DESCRIPTION
**Pull request by vladiouz**
edited config.yaml and network-performance-utility.md

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

- Add Markdown file storing the question scenario and the questions
- Modify `config.yaml` to render the new task

### CODE REVIEW

**Review by teodutu — CHANGES_REQUESTED** [review]
The changes are good.

Now update your commit description to be less vague. Follow the example from this commit [1] and use imperative verbs, not the past tense of the indicative mood.

Second, when you create a PR, you've already seen a template description pop up. Move the description of your changes under the `Description of changes` heading.

**Review by teodutu — COMMENTED** [review]
It's almost good. Use `git rebase -i HEAD~2` to squash the last commit.

Next time you want to fix merge conflicts do the following:
1. Sync your fork's `main` branch with that of cs-pub-ro:
a. `git remote add upb-main git@github.com:cs-pub-ro/operating-systems.git # You only need to run this command once`
b. `git fetch upb-main`
c. `git checkout main`
d. `git pull upb-main main`
1. Rebase the branch for your PR:
a. `git checkout your-branch`
b. `git rebase -i main`
c. The previous command will print the files that have merge conflicts (marked with `>>>>>>` and `<<<<<<`). Fix them and then run `git rebase --continue`. Don't edit your commit message and then run `git push -f` to update the remote branch.

**Comment by vladiouz** [comment]
After I squashed the last commit, conflicts reappeared for this branch. Also, `git fetch upb-main` does not work, saying that I do not have the correct access rights

**Comment by teodutu** [comment]
> After I squashed the last commit, conflicts reappeared for this branch.

That's because you somehow included bot the last commit from `main` and your first commit in this last one. I'm not sure how you got to this point, but I suggest you edit your changes locally to only include the file you want to add in this PR then `git commit --amend` to remove the description and only keep yours.

> Also, `git fetch upb-main` does not work, saying that I do not have the correct access rights

Something's off. You're a member of the OS team [1], so you should have access to the repo. When you encounter errors, copy and paste them here so I can see what they say exactly. But I suspect you might not have the remote repo set properly. What does `git remote -v` print?

**Comment by vladiouz** [comment]
The output of `git remote -v` is:

origin	https://github.com/vladiouz/operating-systems.git (fetch)
origin	https://github.com/vladiouz/operating-systems.git (push)
upb	        git@github.com:cs-pub-ro/hardware-software-interface.git (fetch)
upb	        git@github.com:cs-pub-ro/hardware-software-interface.git (push)
upb-main	git@github.com:cs-pub-ro/operating-systems.git (fetch)
upb-main	git@github.com:cs-pub-ro/operating-systems.git (push)

And the output of `git fetch upb-main` :

Warning: Permanently added the ECDSA host key for IP address '140.82.121.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by teodutu** [comment]
It's not an issue of permissions, but one of keys. Notice the `origin` link with which you cloned the repo uses HTTPS while the others use `git@github.com`, i.e. SSH.

You have 2 options:
1. Add your public SSH key to GitHub like so [1]. I recommend this one as using HTTPS for GitHub is deprecated.
2. `git remote remove upb upb-main` and then `git remote add upb https://github.com/cs-pub-ro/operating-systems.git`.

[1] https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Comment by teodutu** [comment]
I honestly don't understand what caused the checkpatch error. Just rebase the `main` branch to remove the merge conflict and then merge the PR yourself.

**Review by teodutu — APPROVED** [review]

**Pull request merged**
