### PR TITLE
Modify app-interact chapter

### PR DESCRIPTION
**Pull request by cosmin1805**
# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

I will attempt to continue working on:
https://github.com/cs-pub-ro/operating-systems/pull/76

### CODE REVIEW

**Comment by Alex-deVis** [comment]
Hi, @cosmin1805, thanks for this. Please notify me once your PR covers everything from #76 (and its comments) so that I can mark it as superseded by this.

**Review by teodutu — CHANGES_REQUESTED** [review]
In order for your changes to be rendered to the website [1], you'll need to specify the structure of this chapter in `config.yaml` [2], in a way similar to the others ([3] specifies the files used for each lab and [4] specifies the structure of a chapter in the sidebar). To test the website locally, run `make build` in the repo's root folder. Fix the errors, then run `make serve`.

After this, place the slides in their subchapters' `slides/` folders and `slides.mdpp` in `chapters/app-interact/`.

[1] https://cs-pub-ro.github.io/operating-systems/137/
[2] https://github.com/cs-pub-ro/operating-systems/blob/main/config.yaml
[3] https://github.com/cs-pub-ro/operating-systems/blob/5315234f85ee261428c24b0d5249899f1f55530d/config.yaml#L94-L115
[4] https://github.com/cs-pub-ro/operating-systems/blob/5315234f85ee261428c24b0d5249899f1f55530d/config.yaml#L216-L259

**Comment by cosmin1805** [comment]
> In order for your changes to be rendered to the website [1], you'll need to specify the structure of this chapter in `config.yaml` [2], in a way similar to the others ([3] specifies the files used for each lab and [4] specifies the structure of a chapter in the sidebar). To test the website locally, run `make build` in the repo's root folder. Fix the errors, then run `make serve`.
> 
> After this, place the slides in their subchapters' `slides/` folders and `slides.mdpp` in `chapters/app-interact/`.
> 
> [1] https://cs-pub-ro.github.io/operating-systems/137/ [2] https://github.com/cs-pub-ro/operating-systems/blob/main/config.yaml [3]
> 
> https://github.com/cs-pub-ro/operating-systems/blob/5315234f85ee261428c24b0d5249899f1f55530d/config.yaml#L94-L115
> 
> [4]
> 
> https://github.com/cs-pub-ro/operating-systems/blob/5315234f85ee261428c24b0d5249899f1f55530d/config.yaml#L216-L259

What are the titles of Lab 12 and Lab 13? How do I decide the order in which to arrange the tasks, and in which lab each task should be included?

**Comment by teodutu** [comment]
> What are the titles of Lab 12 and Lab 13? How do I decide the order in which to arrange the tasks, and in which lab each task should be included?

There will only be lab 12 for App Interact. You can see the tasks here [1]. Keep them mostly in the same order, but if you feel that any of them would work better in a different place, feel free to move it. Moving tasks around is as easy as moving one line in `config.yaml` so don't worry about making mistakes there, they're easy to fix.

[1] https://github.com/cs-pub-ro/operating-systems/blob/dc21b9b951971d2fcbd08d3562227c2ba60a9c33/config.yaml#L287-L298

**Review by teodutu — CHANGES_REQUESTED** [review]
The chapter's starting to take a better shape now. I made inline suggestions to make things look better. Most of them should be applied globally. In addition, you should also start looking into the checkpatch [1] and super-linter failures [2]. To fix spellcheck, you'll have to add the false positive words [3] to these wordlist via another PR. Make sure to keep those wordlist sorted.

[1] https://github.com/cs-pub-ro/operating-systems/actions/runs/11975236465/job/33388135941?pr=137
[2] https://github.com/cs-pub-ro/operating-systems/actions/runs/11975236465/job/33388135510?pr=137
[3] https://github.com/cs-pub-ro/operating-systems/actions/runs/11975236465/job/33388135058?pr=137

**Review by teodutu — CHANGES_REQUESTED** [review]
I made some more inline comments about splitting the content. Besides, fix the linter failures [1] (I gave further details here [2]), remove `content/chapters/app-interact/` and these comments [3].

[1] https://github.com/cs-pub-ro/operating-systems/pull/137/checks
[2] https://github.com/cs-pub-ro/operating-systems/pull/137/#pullrequestreview-2454994254
[3] https://github.com/cs-pub-ro/operating-systems/blob/main/config.yaml#L331-L348

**Comment by teodutu** [comment]
Also rebase the `main` branch to fix the merge conflict.

**Comment by teodutu** [comment]
Rebase the `main` branch to fix the merge conflicts. In doing so, you can already squash your commits into a single one.

**Comment by cosmin1805** [comment]
So on the branch `translate_app-interact` I did `git rebase upstream/main`, and now i get this
```terminal
hulk-buster@stark-industries-hq:~/sync/FACULTATE/SO/operating-systems$ git status
On branch translate_app-interact
Your branch and 'origin/translate_app-interact' have diverged,
and have 21 and 19 different commits each, respectively.
  (use "git pull" if you want to integrate the remote branch with yours)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.vscode/

nothing added to commit but untracked files present (use "git add" to track)
```
What should I do now?

> Rebase the `main` branch to fix the merge conflicts. In doing so, you can already squash your commits into a single one.

**Comment by teodutu** [comment]
> What should I do now?

Run `git push -f` to update the remote branch with your local changes. You need `-f` because the histories of the remote and local branches have now diverged.

**Review by teodutu — CHANGES_REQUESTED** [review]
The content is good as it is. Now for the finishing touches:
- Add a note like this at the end of each task:
```
If you're having difficulties solving this exercise, go through [this](link to the relevant section in reading/) reading material.
```
- Remove `overview/guides/demo/common/`. All those makefiles should be copied into those that `include` them.
- Move everything in `overview/guides/demo` to `overview/guides/` (and remove `demo/`). A guide is a demo, there's no difference.
- Fix the linter failures [1]. Lots of them come from the logger. Just copy them from the I/O chapter [2] where their coding style has been fixed.
- Your PR shouldn't make any changes to the `io` chapter. Make sure you've rebased properly against the `main` branch that it's updated from the upstream repo:
```
git remote add upstream git@github.com:cs-pub-ro/operating-systems.git

git checkout main

git fetch upstream

git pull upstream main

git checkout translate_app-interact

git rebase -i main  # at this step you can change the first word from each commit from "pick" to "s" (from "squash") so you only end up with one commit after rebasing

# Now the rebase will progress and stop whenever there are conflicts. git will tell you what the conflicting files are. Fix them, then run git add + git rebase --continue until the rebase finishes.

git push -f
```

[1] https://github.com/cs-pub-ro/operating-systems/actions/runs/12241792610/job/34157993777
[2] https://github.com/cs-pub-ro/operating-systems/tree/main/chapters/io/ipc/drills/tasks/receive-challenges/solution/src/utils

**Review by teodutu — CHANGES_REQUESTED** [review]
Here's what I think needs to be done for this to work. After you've done all that, run all tasks and guides to make sure the scripts are working properly:

- Change your commit message to `chapters/io: Refactor content for the OpenEducationHub methodology` followed by a unitary description of what you did + the Signed-off-by line at the end.
- Add a sentence at the beginning of each task that specifies where students should navigate to find the required scripts.
- Change the initial heading of all files that use `##` to `#` (and all the other headings in those files so that the difference between 2 subsequent ones is no more than one `#` - so don't go from `#` to `###` for example).
- Make all shell scripts executable.
- The slides mention demo paths as `demo/demo-name/demo_file`. Update them to reference the correct paths in `guides/demo-name/demo_file`.
- Manually remove the files added by your PR to the `io`/ chapter. I think you added them by mistake some time ago, they changed in the upstream repo and now your PR has them as new additions. Don't remove the whole `io` chapter, just the files added by this PR. You can do this by running this command from the root of the repo:

```
git diff --name-only upb-main | grep 'io/' | xargs git rm -rf
```
And that's why you don't run `git add .`. Add files or folders individually.

**Comment by teodutu** [comment]
After addressing my comments from above, fix the remaining checkpatch [1] and super-linter [2] failures

[1] https://web.facebook.com/george.simion.unire/posts/pfbid02KU4YRzoTU52rJRpRiiDV15coR7pGyBBEyWrtTNsBZEAuQAncvAyTpjSxeG55TH3Wl
[2] https://github.com/cs-pub-ro/operating-systems/actions/runs/12300467630/job/34328705830?pr=137

**Comment by cosmin1805** [comment]
@teodutu should I make all the scripts executable or just the ones you mentioned?

**Comment by cosmin1805** [comment]
@teodutu and @Alex-deVis I fixed what I could what is left now is some errors from the io chapter, witch I did rebase but something is still wrong and some that I don't know if I should fix, like:

```terminal
WARNING:REPEATED_WORD: Possible repeated word: 'slice'
#979: FILE: chapters/app-interact/os-cloud/drills/tasks/os-cloud/README.md:37:
+[ OK ] Removed slice Slice /system/modprobe.
Error: WARNING:REPEATED_WORD: Possible repeated word: 'slice'
```

```terminal
2024-12-12 19:34:36 [INFO]   File:[/github/workspace/chapters/app-interact/os-cloud/drills/tasks/os-cloud/solution/keys/ssh_key]
2024-12-12 19:34:36 [ERROR]   Found errors in [gitleaks] linter!
2024-12-12 19:34:36 [ERROR]   Error code: 1. Command output:
------
Finding:     -----BEGIN OPENSSH PRIVATE KEY-----                                
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdz...-
Secret:      -----BEGIN OPENSSH PRIVATE KEY-----                                
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdz...
RuleID:      private-key
Entropy:     5.992806
File:        /github/workspace/chapters/app-interact/os-cloud/drills/tasks/os-cloud/solution/keys/ssh_key
Line:        1
Fingerprint: /github/workspace/chapters/app-interact/os-cloud/drills/tasks/os-cloud/solution/keys/ssh_key:private-key:1
```

```terminal
2024-12-12 19:37:07 [ERROR]   Found errors in [textlint] linter!
2024-12-12 19:37:07 [ERROR]   Error code: 1. Command output:
------

/github/workspace/chapters/app-interact/os-cloud/reading/os-cloud.md
  460:14  ✓ error  Incorrect usage of the term: “Internet”, use “internet” instead  terminology

✖ 1 problem (1 error, 0 warnings)
✓ 1 fixable problem.
```
This one is a the tittle of the file

```terminal
2024-12-12 19:37:21 [ERROR]   Found errors in [black] linter!
2024-12-12 19:37:21 [ERROR]   Error code: 1. Command output:
------
--- /github/workspace/gen-view.py	2024-12-12 19:34:15.111193 +0000
+++ /github/workspace/gen-view.py	2024-12-12 19:37:21.063104 +0000
@@ -69,10 +69,11 @@
 
     for root, _, files in os.walk(CHAPTERS_PATH):
         for f in files:
             if "questions" in root:
                 os.popen(f"cp {os.path.join(root, f)} {questionsDir}/")
+
 
 def group_guides():
     """
     Group all the guides README.md files in a single directory.
     """
would reformat /github/workspace/gen-view.py
```

**Review by teodutu — COMMENTED** [review]
That's true, some CI/CD errors won't make sense. Ignore those that don't and fix the others.

You removed a good portion of the spurious files from the I/O chapter. For the rest, you can run `git checkout main -- chapters/io/`. and that should synch your local `io/` chapter with the one on `main`.

**Comment by Alex-deVis** [comment]
@cosmin1805 I force-pushed your branch to fix the chekpatch. You probably had an outdated local `main` branch and therefore `git checkout main -- chapters/io` didn't solve the issue. Additionally, you should've ensured that your local `main` is on par with the remote.
Anyway, remember to fetch the latest ref before making additional changes:
```bash
git fetch
git reset --hard <remote-name>/translate_app-interact
```

**Comment by cosmin1805** [comment]
@teodutu  Everything looks good now. I also committed the last change I forgot to make earlier. Should I squash all the commits into one?

**Comment by Alex-deVis** [comment]
The `Create a New Disk by Hand` task does not make sense on its own. Move it back inside `os-cloud` for now, without the `Task` prefix (only change its first heading to `## Task: Create a New Disk by Hand`). This way, it would be a little more obvious that you need to go through the entire `OS cloud` section to solve it.
Other things you could do to improve clarity:
- Create a guide named `Containers vs VMs` comprising of everything inside the current `containers vs vms` and `containers` subchapters.
- Move the `More Implementation Details` and `(Even More) Implementation Details` to the end of `OS Cloud`
- Move the `The X Window System` to the top of the reading materials - it is quite easy and nice to know how the display manager works.

Ignore the current issues in `superlinter` CI, we'll merge regardless after you finish the above items.

**Comment by cosmin1805** [comment]
> Almost there, @cosmin1805, just a few more high-level changes.
> 
> The `Create a New Disk by Hand` task does not make sense on its own. Move it back inside `os-cloud` for now, without the `Task` prefix (only change its first heading to `## Task: Create a New Disk by Hand`). This way, it would be a little more obvious that you need to go through the entire `OS cloud` section to solve it. Other things you could do to improve clarity:
> 
>     * Create a guide named `Containers vs VMs` comprising of everything inside the current `containers vs vms` and `containers` subchapters.
> 
>     * Move the `More Implementation Details` and `(Even More) Implementation Details` to the end of `OS Cloud`
> 
>     * Move the `The X Window System` to the top of the reading materials - it is quite easy and nice to know how the display manager works.
> 
> 
> Ignore the current issues in `superlinter` CI, we'll merge regardless after you finish the above items.

@Alex-deVis  I’ve completed all the requested changes. However, I had a few questions about moving the ## Task: Create a New Disk by Hand section. Could you please confirm if I’ve placed it correctly or suggest any adjustments I should make?

**Review by Alex-deVis — APPROVED** [review]

**Review by teodutu — APPROVED** [review]

**Pull request merged**
