### PR TITLE
general/drills: Add "Digital Forensics" written task as exam

### PR DESCRIPTION
**Pull request by teodutu**
# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

- Add Markdown file storing the question scenario and questions
- Modify `config.yaml` to render the new task
- Update Labeler action to assign the `topic/general` label

### CODE REVIEW

**Review by StefanJum — COMMENTED** [review]
@teodutu is there a reason to add the `true/false` answers and `textbox` arguments to the questions? They are always the same, I don't see a point in adding them.

**Comment by vladiouz** [comment]
I see that you already mentioned the responses structure in the begging (lines 10 and 11), so if you want to make the document simpler, I think a nice alternative would be to just have the questions like this:

1. The application must be run in privileged mode, as root.
2. During its execution, the application does not make system calls.
3. etc. etc.

**Comment by teodutu** [comment]
The structure is like this the file maps to the converter we use to obtain a Moodle XML (MXML) file from Markdown [1]. MXML is the format in which a question can be imported from a file into Moodle. The converter uses the `##` tags to identify tags, difficulty levels, the text of the question, its answers etc.

However, I do admit that structuring the questions in this manner makes it difficult for students to go through them and practice. @razvand would you be OK to store them in a more readable format as suggested by @vladiouz [2] and import them "manually" into Moodle? Otherwise, it would be not easy to create a converter that can figure out generically where the scenario ends and where each question begins.



[1] https://github.com/open-education-hub/openedu-qconv
[2] https://github.com/cs-pub-ro/operating-systems/pull/53#issuecomment-1974849527

**Comment by StefanJum** [comment]
> it would be not easy to create a converter that can figure out generically where the scenario ends and where each question begins.

All the exam questions have the same format now. We can hardcode the convertor to use this format when some option is given (e.g. `--exam`). I know it's not ideal, but the rendering looks way too unnecessarily ugly now.

**Comment by teodutu** [comment]
Take another look. I've updated the structure. I made a separate commit so the older version be more easily accessible.

**Review by vladiouz — APPROVED** [review]

**Review by StefanJum — COMMENTED** [review]
Looks fine to me now. Should we also add the justification along with the answer?

**Comment by teodutu** [comment]
> Should we also add the justification along with the answer?

I don't think so. This is likely to encourage students to copy-paste answers from here to their exams even more so than they're already doing now. Without adding justifications, at least we encourage them to come up with their own solutions and tweak them over time.

**Pull request merged**
