### PR TITLE
software-stack/lab: Remove backticks

### PR DESCRIPTION
**Pull request by PetruCristian**
Word should be past participle, not syscall name.

### CODE REVIEW

**Review by teodutu — CHANGES_REQUESTED** [review]
Thanks for the fix! What you need to do to make the checkpatch test pass [1] is to add the following line to your commit message:

```
Signed-off-by: <Your Name> <your email>
```

To do so, configure your user name and email like so:
```
git config --global user.name "Your Name"
git config --global user.email "your email"
```

Then run `git commit --amend -s` to add the signed-off line automatically to your last commit. Finally, use `git push -f` to replace your existing upstream commit with the one you've just amended. Then check the workflow runs to be all green.

[1] https://github.com/cs-pub-ro/operating-systems/actions/runs/6576723181/job/17866991858?pr=9#step:3:566

**Review by teodutu — APPROVED** [review]
:+1:

Do you know what caused the previous commit to fail checkpatch [1]? Specifically, why did the script want `"petru.nania" <petru.nania@stud.acs.upb.ro>` to be your name and email? Where did it get those?

[1] https://github.com/cs-pub-ro/operating-systems/actions/runs/6578289290/job/17873100587#step:3:566

**Comment by PetruCristian** [comment]
I authored the original commit with my university credentials I had been using for my operating systems assignment. I later changed to my personal credentials when signing off the commit but forgot to change the author's details.

Sent from Yahoo Mail on Android 
 
  On Thu, 19 Oct 2023 at 22:48, Teodor ***@***.***> wrote:   


@teodutu approved this pull request.

👍

Do you know what caused the previous commit to fail checkpatch [1]? Specifically, why did the script want "petru.nania" ***@***.***> to be your name and email? Where did it get those?

[1] https://github.com/cs-pub-ro/operating-systems/actions/runs/6578289290/job/17873100587#step:3:566

**Comment by teodutu** [comment]
Makes sense. Thanks.

**Pull request merged**
