### PR TITLE
chapters/io: Add checker infrastructure for lab 10

### PR DESCRIPTION
**Pull request by Viktor09**
# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/cs-pub-ro/operating-systems/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

Add checkers for lab 10

### CODE REVIEW

**Review by teodutu — CHANGES_REQUESTED** [review]
Thanks for the checkers. Now add instructions about running the checkers along with a snippet with its output with all tests passing to each task's `README.md`.

**Comment by teodutu** [comment]
You haven't applied my changes yet.

**Review by teodutu — APPROVED** [review]

**Comment by teodutu** [comment]
@robertpaulp please add your review.

**Review by robertpaulp — APPROVED** [review]
Looks good. GJ!

**Pull request merged**
